name: AI Models Scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch all history for proper git operations
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run scraper
      id: scraper
      continue-on-error: true  # Continue even if scraper fails
      run: |
        python -c "from scrapers.ai_models_scraper import run_spider; run_spider()"
        
    - name: Check for changes
      id: git-check
      run: |
        git status --porcelain models.json | grep -q "models.json" && echo "::set-output name=changed::true" || echo "::set-output name=changed::false"
        
    - name: Commit and push if changes exist
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add models.json
        git commit -m "Update AI models data [automated]"
        git push
        
    - name: Check scraper status
      if: steps.scraper.outcome == 'failure'
      run: |
        echo "Scraper failed but workflow continued. Check logs for details."
        exit 0  # Don't fail the workflow
